[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
auto_detect_remappings = false
remappings_location = "txt"
solc = '0.8.29'
evm_version = 'paris'
gas_limit = "18446744073709551615"
memory_limit = 33554432
optimizer = true
optimizer_runs = 195
via_ir = true


[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismSepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
polygonMumbai = "${POLYGON_MUMBAI_RPC_URL}"
bnbChainTestnet = "${BNB_CHAIN_TESTNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
metisSepolia = "${METIS_SEPOLIA_RPC_URL}"
zksyncSepolia = "${ZKSYNC_SEPOLIA_RPC_URL}"
scrollSepolia = "${SCROLL_SEPOLIA_RPC_URL}"
zircuitSepolia = "${ZIRCUIT_SEPOLIA_RPC_URL}"
xlayerSepolia = "${XLAYER_SEPOLIA_RPC_URL}"
polygonZkevmSepolia = "${POLYGON_ZKEVM_SEPOLIA_RPC_URL}"
polkadotAstarShibuya = "${POLKADOT_ASTAR_SHIBUYA_RPC_URL}"
mantleSepolia = "${MANTLE_SEPOLIA_RPC_URL}"
soneiumMinatoSepolia = "${SONEIUM_MINATO_SEPOLIA_RPC_URL}"
bsquaredTestnet = "${BSQUARED_TESTNET_RPC_URL}"
bobSepolia = "${BOB_SEPOLIA_RPC_URL}"
worldchainSepolia = "${WORLDCHAIN_SEPOLIA_RPC_URL}"
shibariumTestnet = "${SHIBARIUM_TESTNET_RPC_URL}"
bitlayerTestnet= "${BITLAYER_TESTNET_RPC_URL}"
fantomSonicTestnet = "${FANTOM_SONIC_TESTNET_RPC_URL}"
cornTestnet = "${CORN_TESTNET_RPC_URL}"
hashkeySepolia = "${HASHKEY_SEPOLIA_RPC_URL}"
inkSepolia = "${INK_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
